"""Add subscription fields and fix camera unique constraint

Revision ID: 87aef9680959
Revises: a94de483e0e9
Create Date: 2025-12-02 15:17:27.149012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87aef9680959'
down_revision: Union[str, Sequence[str], None] = 'a94de483e0e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cameras_name'), table_name='cameras')
    op.create_index(op.f('ix_cameras_name'), 'cameras', ['name'], unique=False)
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('expiration_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'expiration_date')
    op.drop_column('users', 'is_active')
    op.drop_index(op.f('ix_cameras_name'), table_name='cameras')
    op.create_index(op.f('ix_cameras_name'), 'cameras', ['name'], unique=True)
    # ### end Alembic commands ###
